#escape sequence 
print("\\n")
print("Muzammil yassen \n son of ghulam yaseen")
print("\\t")
print("Muzammil yassen \t son of ghulam yaseen")
print("\\b")
print("Muzammil yassen \b son of ghulam yaseen")
print("\\r")
print("Muzammil yassen \r son of ghulam yaseen")
print("\\f")
print("Muzammil yassen \f son of ghulam yaseen")
print("\\v")
print("Muzammil yassen \v son of ghulam yaseen")
print("\\a")
print("Muzammil yassen \a son of ghulam yaseen")
print("\\\\")
print("Muzammil yassen \\\\ son of ghulam yaseen")
